export const bestSeller = [
  {
    id: 1,
    title: "White Whole 150",
    description: "Premium large white whole cashews in W150 grade.",
    price: 600,
    weight: "250 g",
    img: "/products/Wholes/w150.png",
  },
  {
    id: 2,
    title: "White Whole 180",
    description: "Fresh and high-quality white whole cashews in W180 grade.",
    price: 550,
    weight: "250 g",
    img: "/products/Wholes/w180.png",
  },
  {
    id: 3,
    title: "Dry Roasted (W-320)",
    description: "Smaller cashews (W-320 grade), roasted for a light and crispy snack.",
    price: 425,
    weight: "250 g",
    img: "/products/Dry Roasted/DR-S.png",
  },
  {
    id: 4,
    title: "Crunchy Butter",
    description: "Buttery goodness with a delightful & chunky crunch in every bite.",
    price: 200,
    weight: "200 g",
    img: "/products/Butter/crunchy.png",
  },
  {
    id: 5,
    title: "Garlic Chilli Flavoured Roasted Cashews",
    description: "Zesty roasted cashews with bold garlic and chilli flavors.",
    price: 300,
    weight: "100 g",
    img: "/products/Flavoured/garlic.png",
  },
  {
    id: 6,
    title: "4 Pieces Cashew",
    description: "Delicious cashew nuts split into 4 pieces, perfect for recipes.",
    price: 240,
    weight: "250 g",
    img: "/products/Pieces/bb.png",
  },
]